spring.application.name=maiv_java

# DB
spring.datasource.url=jdbc:h2:mem:maivdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=maivdb

# H2
spring.h2.console.enabled=true

# Ollama
ollama.url=http://localhost:11434/api/chat

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true